# Generated by Django 4.2 on 2023-04-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do anime')),
                ('resumo', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Resumo do anime')),
                ('tipo', models.CharField(choices=[('0', 'Anime'), ('1', 'Mangá'), ('2', 'Jogo')], default='Anime', max_length=15, verbose_name='Tipo de obra')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Usuario')),
                ('biografia', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Biografia do Usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo da lista')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.usuario')),
                ('obras', models.ManyToManyField(blank=True, to='webapp.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Comentarios')),
                ('nota', models.IntegerField(default=0, max_length=10, verbose_name='Nota da obra')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.usuario')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.obra')),
            ],
        ),
    ]
