# Generated by Django 4.2 on 2023-04-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizacao', models.CharField(max_length=250, verbose_name='Descrição da atualizacao')),
                ('referencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Classe+ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.usuario')),
            ],
        ),
    ]
